###
POST http://localhost:8080/alunos
Content-Type: application/json

{
    "nome": "Andre",
    "cpf": "096.004.814-66",
    "dataDeNascimento": "11/10/1991",
    "bairro": "Potengi"
}

###

POST http://localhost:8080/avaliacoes
Content-Type: application/json

{
    "alunoId": "1",
    "peso": "64.0",
    "altura": "171.5"
}

###
GET http://localhost:8080/alunos/avaliacoes/1


###
DELETE http://localhost:8080/clientes/9


###
POST http://localhost:8080/clientes
Content-Type: application/json

{
    "nome": "Sousa"
}
